export const
hiraganaSamples =[
    {display:"オンライン",answer:"onrainn"},
    {display:"日本地図",answer:"nihonntizu"},
    {display:"珍獣",answer:"tinzyuu"},
    {display:"もらい泣き",answer:"morainaki"},
    {display:"ホウセンカ",answer:"housenka"},
    {display:"水彩画",answer:"suisaiga"},
    {display:"あまのじゃく",answer:"amanozyaku"},
    {display:"リコーダー",answer:"riko-da-"},
    {display:"バイオリン",answer:"baiorin"},
    {display:"ハーモニカ",answer:"ha-monika"},
    {display:"ストラップ",answer:"sutorappu"},
    {display:"メンチカツ",answer:"mentikatu"},
    {display:"オムライス",answer:"omuraisu"},
    {display:"英単語",answer:"eitango"},
    {display:"アクセント",answer:"akusento"},
    {display:"腕時計",answer:"udedokei"},
    {display:"台所",answer:"daidokoro"},
    {display:"フライパン",answer:"huraipann"},
    {display:"りんご飴",answer:"ringoame"},
    {display:"カレンダー",answer:"karenda-"},
    {display:"チャンピオン",answer:"tyanpion"},
    {display:"ビーチボール",answer:"bi-tibo-ru"},
    {display:"国語辞典",answer:"kokugozitenn"},
    {display:"色鉛筆",answer:"iroenpitu"},
    {display:"図書委員",answer:"toshoiinn"},
    {display:"送りバント",answer:"okuribanto"},
    {display:"羊の群れ",answer:"hituzinomure"},
    {display:"カスタネット",answer:"kasutanetto"},
    {display:"四季折々",answer:"sikioriori"},
    {display:"万華鏡",answer:"mangekyou"},
    {display:"大河ドラマ",answer:"taigadorama"},
    {display:"引っ張りだこ",answer:"hipparidako"},
    {display:"道に迷う",answer:"mitinimayou"},
    {display:"フルマラソン",answer:"hurumarasonn"},
    {display:"会議中",answer:"kaigityuu"},
    {display:"チキンカレー",answer:"tikinkare-"},
    {display:"猫に小判",answer:"nekonikobann"},
    {display:"ト音記号",answer:"toonkigou"},
    {display:"寝耳に水",answer:"nemiminimizu"},
    {display:"中古車",answer:"tyuukosha"},
    {display:"電話帳",answer:"denwatyou"},
    {display:"体操服",answer:"taisouhuku"},
    {display:"心理テスト",answer:"sinritesuto"},
    {display:"ヒッチハイク",answer:"hittihaiku"},
    {display:"水平線",answer:"suiheisenn"},
    {display:"竜頭蛇尾",answer:"ryuutoudabi"},
    {display:"遺産相続",answer:"isansouzoku"},
    {display:"ラジオ体操",answer:"raziotaisou"},
    {display:"完全試合",answer:"kanzensiai"},
    {display:"バウムクーヘン",answer:"baumuku-henn"},
    {display:"縄文土器",answer:"zyoumondoki"},
    {display:"梅雨前線",answer:"baiuzensenn"},
    {display:"大和魂",answer:"yamatodamasii"},
    {display:"北斗七星",answer:"hokutositisei"},
    {display:"北欧神話",answer:"hokuousinwa"},
    {display:"万葉集",answer:"mannyoushuu"},
    {display:"消える魔球",answer:"kierumakyuu"},
    {display:"間違い探し",answer:"matigaisagasi"},
    {display:"複雑怪奇",answer:"hukuzatukaiki"},
    {display:"ホワイトボード",answer:"howaitobo-do"},
    {display:"テレビ番組",answer:"terebibangumi"},
    {display:"鬼に金棒",answer:"oninikanabou"},
    {display:"待ち受け画面",answer:"matiukegamenn"},
    {display:"人気タレント",answer:"ninkitarento"},
    {display:"サッカーゴール",answer:"sakka-go-ru"},
    {display:"研修会",answer:"kenshuukai"},
    {display:"宅急便",answer:"takkyuubinn"},
    {display:"ジグソーパズル",answer:"ziguso-pazuru"},
    {display:"ロングスカート",answer:"rongusuka-to"},
    {display:"インフルエンザ",answer:"inhuruennza"},
    {display:"迷える子羊",answer:"mayoerukohituzi"},
    {display:"産地直送",answer:"santityokusou"},
    {display:"全席禁煙",answer:"zensekikinnenn"},
    {display:"起承転結",answer:"kishoutenketu"},
    {display:"東洋の魔女",answer:"touyounomazyo"},
    {display:"美女と野獣",answer:"bizyotoyazyuu"},
    {display:"兄弟げんか",answer:"kyoudaigenka"},
    {display:"身体測定",answer:"sintaisokutei"},
    {display:"百万ボルト",answer:"hyakumanboruto"},
    {display:"一撃必殺",answer:"itigekihissatu"},
    {display:"天国と地獄",answer:"tengokutozigoku"},
    {display:"ボディランゲージ",answer:"bodhirange-zi"},
    {display:"ドラゴンフルーツ",answer:"doragonhuru-tu"},
    {display:"心霊スポット",answer:"sinreisupotto"},
    {display:"ブラックコーヒー",answer:"burakkuko-hi-"},
    {display:"全国大会",answer:"zenkokutaikai"},
    {display:"参勤交代",answer:"sankinkoutai"},
    {display:"ヒットエンドラン",answer:"hittoendorann"},
    {display:"現代社会",answer:"gendaishakai"},
    {display:"気象衛星",answer:"kishoueisei"},
    {display:"光陰矢の如し",answer:"kouinnyanogotosi"},
    {display:"ジャイアントパンダ",answer:"zyaiantopanda"},
    {display:"冷凍食品",answer:"reitoushokuhinn"},
    {display:"有酸素運動",answer:"yuusansoundou"},
    {display:"プロフェッショナル",answer:"purofesshonaru"},
    {display:"アメリカンコーヒー",answer:"amerikanko-hi-"},
    {display:"暗証番号",answer:"anshoubangou"},
    {display:"懐中電灯",answer:"kaityuudentou"},
    {display:"戦国大名",answer:"sengokudaimyou"},
    {display:"コマンドプロンプト",answer:"komandopuronputo"}
];












