export const hiraganaSamples2 = [
  {display:"ハロウィンパーティー", answer:"harowinpa-thi-", count: "14"},
  {display:"海上自衛隊", answer:"kaizyouzieitai", count: "14"},
  {display:"星のない夜の空", answer:"hosinonaiyorunosora", count: "19"},
  {display:"ドラマチックな出会い", answer:"doramatikkunadeai", count: "17"},
  {display:"お嬢様学校", answer:"ozyousamagakkou", count: "15"},
  {display:"ドコサヘキサエン酸", answer:"dokosahekisaensann", count: "18"},
  {display:"スキューバダイビング", answer:"sukyu-badaibingu", count: "16"},
  {display:"お遊びはここまでだ", answer:"oasobihakokomadeda", count: "18"},
  {display:"真珠のネックレス", answer:"sinzyunonekkuresu", count: "17"},
  {display:"人生の分岐点", answer:"zinseinobunkitenn", count: "17"},
  {display:"獅子座流星群", answer:"sisizaryuuseigunn", count: "17"},
  {display:"石油ファンヒーター", answer:"sekiyufanhi-ta-", count: "15"},
  {display:"シンデレラストーリー", answer:"sindererasuto-ri-", count: "17"},
  {display:"上昇気流", answer:"zyoushoukiryuu", count: "14"},
  {display:"コンビニエンスストア", answer:"konbiniensusutoa", count: "16"},
  {display:"地球は青かった", answer:"tikyuuhaaokatta", count: "15"},
  {display:"運命の赤い糸", answer:"unmeinoakaiito", count: "14"},
];
